version: '3.3'

services:
   905-fulton-db:
     image: mysql:5.7
     volumes:
       - 905_fulton_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: 905-fulton-db
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
       MYSQL_USER_FILE: /run/secrets/torque_wp_mysql_user
       MYSQL_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
     networks:
       - 905-fulton-back
     secrets:
       - torque_wp_mysql_root
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

   905-fulton-phpmyadmin:
    depends_on:
      - 905-fulton-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: 905-fulton-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
    networks:
      - 905-fulton-back
    secrets:
      - torque_wp_mysql_root

   905-fulton-wordpress:
     depends_on:
       - 905-fulton-db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./wp-content:/var/www/html/wp-content
     restart: always
     environment:
       WORDPRESS_DB_HOST: 905-fulton-db:3306
       WORDPRESS_DB_NAME: 905-fulton-db
       WORDPRESS_DB_USER_FILE: /run/secrets/torque_wp_mysql_user
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
       WORDPRESS_DEBUG: 1
     networks:
       - 905-fulton-back
     secrets:
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

networks:
  905-fulton-back:

volumes:
  905_fulton_db_data:
    driver: local

secrets:
  torque_wp_mysql_root:
    file: ./secrets/mysql_root.txt
  torque_wp_mysql_user:
    file: ./secrets/mysql_user.txt
  torque_wp_mysql_pass:
    file: ./secrets/mysql_pass.txt
