version: '3.1'

services:
   the-cannery-db:
     image: mysql:5.7
     volumes:
       - the_cannery_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: torque-wp-the-cannery
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
       MYSQL_USER_FILE: /run/secrets/torque_wp_mysql_user
       MYSQL_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
     networks:
       - the-cannery-back
     secrets:
       - torque_wp_mysql_root
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

   phpmyadmin:
    depends_on:
      - the-cannery-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: the-cannery-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
    networks:
      - the-cannery-back
    secrets:
      - torque_wp_mysql_root

   wordpress:
     depends_on:
       - the-cannery-db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./php.ini:/var/www/html/php.ini
     restart: always
     environment:
       WORDPRESS_DB_HOST: the-cannery-db:3306
       WORDPRESS_DB_NAME: torque-wp-the-cannery
       WORDPRESS_DB_USER_FILE: /run/secrets/torque_wp_mysql_user
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
       WORDPRESS_DEBUG: 1
     networks:
       - the-cannery-back
     secrets:
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

networks:
  the-cannery-back:

volumes:
  the_cannery_db_data:
    driver: local

secrets:
  torque_wp_mysql_root:
    file: ./secrets/mysql_root.txt
  torque_wp_mysql_user:
    file: ./secrets/mysql_user.txt
  torque_wp_mysql_pass:
    file: ./secrets/mysql_pass.txt
