version: '3.3'

services:
   s333-db:
     image: mysql:5.7
     volumes:
       - s333_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: s333-wp
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
       MYSQL_USER_FILE: /run/secrets/torque_wp_mysql_user
       MYSQL_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
     networks:
       - s333-back
     secrets:
       - torque_wp_mysql_root
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

   s222-phpmyadmin:
    depends_on:
      - s333-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: s333-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
    networks:
      - s333-back
    secrets:
      - torque_wp_mysql_root

   s222-wordpress:
     depends_on:
       - s333-db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./php.ini:/var/www/html/php.ini
     restart: always
     environment:
       WORDPRESS_DB_HOST: s333-db:3306
       WORDPRESS_DB_NAME: s333-wp
       WORDPRESS_DB_USER_FILE: /run/secrets/torque_wp_mysql_user
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
       WORDPRESS_DEBUG: 1
     networks:
       - s333-back
     secrets:
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

networks:
  s333-back:

volumes:
  s333_db_data:
    driver: local

secrets:
  torque_wp_mysql_root:
    file: ./secrets/mysql_root.txt
  torque_wp_mysql_user:
    file: ./secrets/mysql_user.txt
  torque_wp_mysql_pass:
    file: ./secrets/mysql_pass.txt
