version: '3.1'

services:

   pacific-residential-db:
     image: mysql:5.7
     ports:
       - "4306:3306"
     volumes:
       - pacific-residential-db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: torque-wp
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
       MYSQL_USER_FILE: /run/secrets/torque_wp_mysql_user
       MYSQL_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
     networks:
       - pacific-residential-back
     secrets:
       - torque_wp_mysql_root
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

   pacific-residential-phpmyadmin:
    depends_on:
      - pacific-residential-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: pacific-residential-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
    networks:
      - pacific-residential-back
    secrets:
      - torque_wp_mysql_root

   pacific-residential-wordpress:
     depends_on:
       - pacific-residential-db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./php.ini:/var/www/html/php.ini
     restart: always
     environment:
       WORDPRESS_DB_HOST: pacific-residential-db:3306
       WORDPRESS_DB_NAME: torque-wp
       WORDPRESS_DB_USER_FILE: /run/secrets/torque_wp_mysql_user
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
       WORDPRESS_DEBUG: 1
     networks:
       - pacific-residential-back
     secrets:
       - torque_wp_mysql_user
       - torque_wp_mysql_pass

networks:
  pacific-residential-back:

volumes:
  pacific-residential-db_data:
    driver: local

secrets:
  torque_wp_mysql_root:
    file: ./secrets/mysql_root.txt
  torque_wp_mysql_user:
    file: ./secrets/mysql_user.txt
  torque_wp_mysql_pass:
    file: ./secrets/mysql_pass.txt
