version: "3.3"

services:
  evoq-db:
    image: mysql:5.7
    volumes:
      - evoq-db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: evoq-wp
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
      MYSQL_USER_FILE: /run/secrets/torque_wp_mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
    networks:
      - evoq-back
    secrets:
      - torque_wp_mysql_root
      - torque_wp_mysql_user
      - torque_wp_mysql_pass

  evoq-phpmyadmin:
    depends_on:
      - evoq-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: evoq-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/torque_wp_mysql_root
    networks:
      - evoq-back
    secrets:
      - torque_wp_mysql_root

  evoq-wordpress:
    depends_on:
      - evoq-db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./php.ini:/var/www/html/php.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: evoq-db:3306
      WORDPRESS_DB_NAME: evoq-wp
      WORDPRESS_DB_USER_FILE: /run/secrets/torque_wp_mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/torque_wp_mysql_pass
      WORDPRESS_DEBUG: 1
    networks:
      - evoq-back
    secrets:
      - torque_wp_mysql_user
      - torque_wp_mysql_pass

networks:
  evoq-back:

volumes:
  evoq-db_data:
    driver: local

secrets:
  torque_wp_mysql_root:
    file: ./secrets/mysql_root.txt
  torque_wp_mysql_user:
    file: ./secrets/mysql_user.txt
  torque_wp_mysql_pass:
    file: ./secrets/mysql_pass.txt
