<?php

// require_once( get_template_directory() . '/includes/acf/torque-acf-search-class.php' );

class IMA_ACF {

  public function __construct() {
    add_action('admin_init', array( $this, 'acf_admin_init'), 99);
    add_action('acf/init', array( $this, 'acf_init' ) );

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    // if ( class_exists( 'Torque_ACF_Search' ) ) {
    //   add_filter( Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array( $this, 'add_fields_to_search' ) );
    // }
  }

  public function acf_admin_init() {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search( $fields ) {
    // $fields[] = 'hero_overlay_title';
    // $fields[] = 'hero_overlay_subtitle';
    // $fields[] = 'page_heading';
    // $fields[] = 'page_intro';
    // $fields[] = 'heading';
    // $fields[] = 'content';

    return $fields;
  }

  public function acf_init() {
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_5dbb3d834f848',
  'title' => 'Disclosure',
  'fields' => array(
    array(
      'key' => 'field_5dbb3d8e544d3',
      'label' => 'PDF',
      'name' => 'pdf',
      'type' => 'file',
      'instructions' => 'Upload a PDF to use for this disclosure.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'library' => 'all',
      'min_size' => '',
      'max_size' => '',
      'mime_types' => 'pdf',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'interra_disclaimer',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d9de6d65a5d3',
  'title' => 'Expenses',
  'fields' => array(
    array(
      'key' => 'field_5d9de814df3ba',
      'label' => 'Taxes',
      'name' => 'taxes',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df2e2df3bc',
      'label' => 'Insurance',
      'name' => 'insurance',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df2fcdf3bd',
      'label' => 'Gas',
      'name' => 'gas',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df305df3be',
      'label' => 'Electric',
      'name' => 'electric',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df315df3bf',
      'label' => 'Water',
      'name' => 'water',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df323df3c0',
      'label' => 'Trash/Scavenger',
      'name' => 'trash',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df333df3c1',
      'label' => 'Elevator',
      'name' => 'elevator',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df370df3c6',
      'label' => 'Extra Expenses',
      'name' => 'extra_expenses',
      'type' => 'repeater',
      'instructions' => 'Insert more expenses as Name = Expense.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Expense',
      'sub_fields' => array(
        array(
          'key' => 'field_5d9df440420a3',
          'label' => 'Expense Name',
          'name' => 'expense_name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d9df44d420a4',
          'label' => 'Expense Amount',
          'name' => 'expense_amount',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '0.00',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5d9df341df3c2',
      'label' => 'Management',
      'name' => 'management',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df34edf3c3',
      'label' => 'Janitorial',
      'name' => 'janitorial',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df357df3c4',
      'label' => 'Turnover Costs',
      'name' => 'turnover_costs',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d9df361df3c5',
      'label' => 'Misc. and Reserves',
      'name' => 'misc_and_reserves',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0.00',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5dbb500a97723',
  'title' => 'Income',
  'fields' => array(
    array(
      'key' => 'field_5dbb501839256',
      'label' => 'Parking Income',
      'name' => 'parking_income',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5dbb506b39257',
      'label' => 'Estimated Vacancy Lost',
      'name' => 'vacancy',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '%',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5dbb50ab39258',
      'label' => 'Laundry',
      'name' => 'laundry',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5dbb50ee39259',
      'label' => 'Pet Fees',
      'name' => 'pet_fees',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5ce8548fef5fd',
  'title' => 'Neighborhoods Order',
  'fields' => array(
    array(
      'key' => 'field_5ce854d7461fb',
      'label' => 'Order Neighborhoods',
      'name' => 'order_neighborhoods',
      'type' => 'repeater',
      'instructions' => 'Select Neighborhoods in the order you want them displayed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Neighborhood',
      'sub_fields' => array(
        array(
          'key' => 'field_5ce85513461fc',
          'label' => 'Neighborhood',
          'name' => 'neighborhood',
          'type' => 'taxonomy',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'taxonomy' => 'interra_listing_property_type',
          'field_type' => 'select',
          'allow_null' => 0,
          'add_term' => 0,
          'save_terms' => 0,
          'load_terms' => 0,
          'return_format' => 'id',
          'multiple' => 0,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d680c6f02e77',
  'title' => 'Proposal Details',
  'fields' => array(
    array(
      'key' => 'field_5d680cb524f6b',
      'label' => 'Project Name',
      'name' => 'project_name',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680ccb24f6c',
      'label' => 'Date of Proposal',
      'name' => 'date_of_proposal',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array(
      'key' => 'field_5d680ce924f6d',
      'label' => 'Client Name(s)',
      'name' => 'client_names',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d680d1424f6e',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Name',
      'sub_fields' => array(
        array(
          'key' => 'field_5d680d1424f6e',
          'label' => 'name',
          'name' => 'name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'John Doe',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d680d4a24f6f',
          'label' => 'Email',
          'name' => 'email',
          'type' => 'email',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'john.doe@email.com',
          'prepend' => '',
          'append' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5d680da724f70',
      'label' => 'Company Name',
      'name' => 'company_name',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680de624f71',
      'label' => 'Broker',
      'name' => 'broker',
      'type' => 'user',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'role' => array(
        0 => 'broker',
      ),
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'object',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d680eb87fc15',
  'title' => 'Property Information',
  'fields' => array(
    array(
      'key' => 'field_5d680ec250076',
      'label' => 'Listing',
      'name' => 'listing',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'torque_listing',
      ),
      'taxonomy' => array(
      ),
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array(
      'key' => 'field_5d680f4150077',
      'label' => 'PIN',
      'name' => 'pin',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680fa350078',
      'label' => 'Building Type',
      'name' => 'building_type',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680fc950079',
      'label' => 'Number of Units',
      'name' => 'number_of_units',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d680fdf5007a',
      'label' => 'Year Built',
      'name' => 'year_built',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d68102f5007b',
      'label' => 'Utilities Paid by Tenant',
      'name' => 'utilities_paid_by_tenant',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'Yes' => 'Yes',
        'No' => 'No',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'default_value' => 'No',
      'layout' => 'horizontal',
      'return_format' => 'value',
      'save_other_choice' => 0,
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 2,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681120abb06',
  'title' => 'Rent Roll',
  'fields' => array(
    array(
      'key' => 'field_5dbc6a0c75469',
      'label' => 'Units Spreadsheet',
      'name' => 'units_spreadsheet',
      'type' => 'file',
      'instructions' => 'Upload a CSV file to import Rent Roll.<br />
<br />
IMPORTANT:<br />
- Always run an import AFTER you have saved all other changes.<br />
- In order for an import to work you must upload a new file. Selecting from files previously uploaded will not work.<br />
- The only file type supported to import Rent Roll data is CSV.<br />
- The CSV file must have the following headers: address | type | total_rooms | sq | rent | lease_expiration | tenant_notes<br />
- Although any CSV file should work, some versions of Microsoft Excel are known to export a CSV format that browsers have trouble reading. To avoid these issues we recommend using Google Spreadsheets to create your CSV imports.<br />
- Uploading a new import WILL REPLACE all data in the Rent Roll table.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'library' => 'all',
      'min_size' => '',
      'max_size' => '',
      'mime_types' => 'csv',
    ),
    array(
      'key' => 'field_5d68112838483',
      'label' => 'Units',
      'name' => 'units',
      'type' => 'repeater',
      'instructions' => 'Add units for rent roll',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Unit',
      'sub_fields' => array(
        array(
          'key' => 'field_5d68117038484',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d6814e438485',
          'label' => 'Type',
          'name' => 'type',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d6814ef38486',
          'label' => 'Total Rooms',
          'name' => 'total_rooms',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5d68151238487',
          'label' => 'Square Footage',
          'name' => 'sq',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => 'sq ft',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d68153138488',
          'label' => 'Rent',
          'name' => 'rent',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d68155238489',
          'label' => 'Lease Expiration',
          'name' => 'lease_expiration',
          'type' => 'date_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'd/m/Y',
          'return_format' => 'd/m/Y',
          'first_day' => 1,
        ),
        array(
          'key' => 'field_5d6815713848a',
          'label' => 'Tenant Notes',
          'name' => 'tenant_notes',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 3,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d5d57d8c1ceb',
  'title' => 'Loan Amortization Details',
  'fields' => array(
    array(
      'key' => 'field_5d5d57fc8de43',
      'label' => 'Term',
      'name' => 'term',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        30 => '30 years',
        25 => '25 years',
        20 => '20 years',
      ),
      'default_value' => array(
        0 => 30,
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'return_format' => 'array',
      'ajax' => 0,
      'placeholder' => '',
    ),
    array(
      'key' => 'field_5d5d58af8de44',
      'label' => 'Down Payment',
      'name' => 'down_payment',
      'type' => 'number',
      'instructions' => 'Please enter a number as a percentage',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 30,
      'placeholder' => 25,
      'prepend' => '',
      'append' => '%',
      'min' => 0,
      'max' => 100,
      'step' => '',
    ),
    array(
      'key' => 'field_5d5d66808de45',
      'label' => 'Property Value',
      'name' => 'property_value',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 0,
      'placeholder' => '9,999,999',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d5d66d98de46',
      'label' => 'Interest Rate',
      'name' => 'interest_rate',
      'type' => 'number',
      'instructions' => 'Please enter the interest rate as a percentage',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 6,
      'placeholder' => 6,
      'prepend' => '',
      'append' => '%',
      'min' => 0,
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 4,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => 'Enter details for loan amortization chart & UI',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681695f3e6c',
  'title' => 'Pictures & Video',
  'fields' => array(
    array(
      'key' => 'field_5d6816b42b358',
      'label' => 'Pictures',
      'name' => 'pictures',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => '',
      'max' => '',
      'insert' => 'append',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'jpg,jpeg,png',
    ),
    array(
      'key' => 'field_5d6817362b359',
      'label' => 'Videos',
      'name' => 'videos',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Video',
      'sub_fields' => array(
        array(
          'key' => 'field_5d6818a21da75',
          'label' => 'Video',
          'name' => 'video',
          'type' => 'text',
          'instructions' => 'Enter a YouTube video ID.
i.e. rpvFXdxaK7o',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5d6817912b35a',
      'label' => '360 Pictures',
      'name' => '360_pictures',
      'type' => 'repeater',
      'instructions' => 'Upload images for use in 360 and Virtual Reality',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add 360 Photo',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681831ad7b4',
          'label' => '360 Photo',
          'name' => 'pano',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'full',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => 'jpg,jpeg,png',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 5,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5c9d4fca4fc93',
  'title' => 'User Relationship',
  'fields' => array(
    array(
      'key' => 'field_5c9d4fd222c78',
      'label' => 'User',
      'name' => 'user',
      'type' => 'user',
      'instructions' => 'Pick a WP user to associate with this staff member. This allows us to display a staff member\'s blog posts by checking the author.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'role' => '',
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'torque_staff',
      ),
    ),
  ),
  'menu_order' => 5,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681a97c7238',
  'title' => 'Maps',
  'fields' => array(
    array(
      'key' => 'field_5d681a9c872e7',
      'label' => 'Maps',
      'name' => 'maps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Map',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681aae872e8',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 6,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681caa470d6',
  'title' => 'Disclaimers',
  'fields' => array(
    array(
      'key' => 'field_5d681cb4a2bfa',
      'label' => 'Disclaimers',
      'name' => 'disclaimers',
      'type' => 'checkbox',
      'instructions' => 'Select the disclosures that should be included in this document.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'dual_agency' => 'dual agency',
        'clean_lp' => 'clean lead paint',
        'dirty_lp' => 'dirty lead paint',
      ),
      'allow_custom' => 0,
      'default_value' => array(
        0 => 'dual_agency',
        1 => 'clean_lp',
      ),
      'layout' => 'horizontal',
      'toggle' => 0,
      'return_format' => 'label',
      'save_custom' => 0,
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 7,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681d03442fc',
  'title' => 'Comps',
  'fields' => array(
    array(
      'key' => 'field_5d681d0871b82',
      'label' => 'Sales Comps',
      'name' => 'sales_comps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d681d2b71b83',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Sales Comp',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681d2b71b83',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d681d3f71b84',
          'label' => 'Price Sold',
          'name' => 'price_sold',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d681d4f71b85',
          'label' => 'Differences',
          'name' => 'differences',
          'type' => 'textarea',
          'instructions' => 'List one difference per line.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5d681d9671b86',
          'label' => 'Photo',
          'name' => 'photo',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5d681da771b87',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
    array(
      'key' => 'field_5d681e4ae17fd',
      'label' => 'Rent Comps',
      'name' => 'rent_comps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d681d2b71b83',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Rent Comp',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681e4ae17fe',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d681e4ae17ff',
          'label' => 'Rent',
          'name' => 'rent',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1800',
          'label' => 'Differences',
          'name' => 'differences',
          'type' => 'textarea',
          'instructions' => 'List one difference per line.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1801',
          'label' => 'Photo',
          'name' => 'photo',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1802',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 8,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681e9b55c1a',
  'title' => 'Taxes',
  'fields' => array(
    array(
      'key' => 'field_5d681ea0720c9',
      'label' => 'Tax Year',
      'name' => 'tax_year',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681eb2720ca',
      'label' => 'Land Assessment',
      'name' => 'land_assessment',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681ef3720cb',
      'label' => 'Building Assesment',
      'name' => 'building_assesment',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681f02720cc',
      'label' => 'Tax Rate',
      'name' => 'tax_rate',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '%',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 9,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;
  }
}

?>
