<?php

// require_once( get_template_directory() . '/includes/acf/torque-acf-search-class.php' );

class IMA_ACF {

  public function __construct() {
    add_action('admin_init', array( $this, 'acf_admin_init'), 99);
    add_action('acf/init', array( $this, 'acf_init' ) );

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    // if ( class_exists( 'Torque_ACF_Search' ) ) {
    //   add_filter( Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array( $this, 'add_fields_to_search' ) );
    // }
  }

  public function acf_admin_init() {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search( $fields ) {
    // $fields[] = 'hero_overlay_title';
    // $fields[] = 'hero_overlay_subtitle';
    // $fields[] = 'page_heading';
    // $fields[] = 'page_intro';
    // $fields[] = 'heading';
    // $fields[] = 'content';

    return $fields;
  }

  public function acf_init() {
    if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_5d680c6f02e77',
  'title' => 'Proposal Details',
  'fields' => array(
    array(
      'key' => 'field_5d680cb524f6b',
      'label' => 'Project Name',
      'name' => 'project_name',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680ccb24f6c',
      'label' => 'Date of Proposal',
      'name' => 'date_of_proposal',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array(
      'key' => 'field_5d680ce924f6d',
      'label' => 'Client Name(s)',
      'name' => 'client_names',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d680d1424f6e',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Name',
      'sub_fields' => array(
        array(
          'key' => 'field_5d680d1424f6e',
          'label' => 'name',
          'name' => 'name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'John Doe',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d680d4a24f6f',
          'label' => 'Email',
          'name' => 'email',
          'type' => 'email',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'john.doe@email.com',
          'prepend' => '',
          'append' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5d680da724f70',
      'label' => 'Company Name',
      'name' => 'company_name',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680de624f71',
      'label' => 'Broker',
      'name' => 'broker',
      'type' => 'user',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'role' => array(
        0 => 'broker',
      ),
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'object',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d680eb87fc15',
  'title' => 'Property Information',
  'fields' => array(
    array(
      'key' => 'field_5d680ec250076',
      'label' => 'Listing',
      'name' => 'listing',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'torque_listing',
      ),
      'taxonomy' => array(
      ),
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array(
      'key' => 'field_5d680f4150077',
      'label' => 'PIN',
      'name' => 'pin',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680fa350078',
      'label' => 'Building Type',
      'name' => 'building_type',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5d680fc950079',
      'label' => 'Number of Units',
      'name' => 'number_of_units',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d680fdf5007a',
      'label' => 'Year Built',
      'name' => 'year_built',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d68102f5007b',
      'label' => 'Utilities Paid by Tenant',
      'name' => 'utilities_paid_by_tenant',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'Yes' => 'Yes',
        'No' => 'No',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'default_value' => 'No',
      'layout' => 'horizontal',
      'return_format' => 'value',
      'save_other_choice' => 0,
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 2,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681120abb06',
  'title' => 'Rent Roll',
  'fields' => array(
    array(
      'key' => 'field_5d68112838483',
      'label' => 'Units',
      'name' => 'units',
      'type' => 'repeater',
      'instructions' => 'Add units for rent roll',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Unit',
      'sub_fields' => array(
        array(
          'key' => 'field_5d68117038484',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d6814e438485',
          'label' => 'Type',
          'name' => 'type',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d6814ef38486',
          'label' => 'Total Rooms',
          'name' => 'total_rooms',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5d68151238487',
          'label' => 'Square Footage',
          'name' => 'sq',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => 'sq ft',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d68153138488',
          'label' => 'Rent',
          'name' => 'rent',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d68155238489',
          'label' => 'Lease Expiration',
          'name' => 'lease_expiration',
          'type' => 'date_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'd/m/Y',
          'return_format' => 'd/m/Y',
          'first_day' => 1,
        ),
        array(
          'key' => 'field_5d6815713848a',
          'label' => 'Tenant Notes',
          'name' => 'tenant_notes',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 3,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d5d57d8c1ceb',
  'title' => 'Loan Amortization Details',
  'fields' => array(
    array(
      'key' => 'field_5d5d57fc8de43',
      'label' => 'Term',
      'name' => 'term',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        30 => '30 years',
        15 => '15 years',
      ),
      'default_value' => array(
        0 => 30,
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'return_format' => 'array',
      'ajax' => 0,
      'placeholder' => '',
    ),
    array(
      'key' => 'field_5d5d58af8de44',
      'label' => 'Down Payment',
      'name' => 'down_payment',
      'type' => 'number',
      'instructions' => 'Please enter a number as a percentage',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 30,
      'placeholder' => 25,
      'prepend' => '',
      'append' => '%',
      'min' => 0,
      'max' => 100,
      'step' => '',
    ),
    array(
      'key' => 'field_5d5d66808de45',
      'label' => 'Property Value',
      'name' => 'property_value',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 0,
      'placeholder' => '9,999,999',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d5d66d98de46',
      'label' => 'Interest Rate',
      'name' => 'interest_rate',
      'type' => 'number',
      'instructions' => 'Please enter the interest rate as a percentage',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 6,
      'placeholder' => 6,
      'prepend' => '',
      'append' => '%',
      'min' => 0,
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 4,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => 'Enter details for loan amortization chart & UI',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681695f3e6c',
  'title' => 'Pictures & Video',
  'fields' => array(
    array(
      'key' => 'field_5d6816b42b358',
      'label' => 'Pictures',
      'name' => 'pictures',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => '',
      'max' => '',
      'insert' => 'append',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'jpg,jpeg,png',
    ),
    array(
      'key' => 'field_5d6817362b359',
      'label' => 'Videos',
      'name' => 'videos',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Video',
      'sub_fields' => array(
        array(
          'key' => 'field_5d6818a21da75',
          'label' => 'Video',
          'name' => 'video',
          'type' => 'text',
          'instructions' => 'Enter a YouTube video ID.
i.e. rpvFXdxaK7o',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
    array(
      'key' => 'field_5d6817912b35a',
      'label' => '360 Pictures',
      'name' => '360_pictures',
      'type' => 'repeater',
      'instructions' => 'Upload images for use in 360 and Virtual Reality',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add 360 Photo',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681831ad7b4',
          'label' => '360 Photo',
          'name' => 'pano',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'full',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => 'jpg,jpeg,png',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 5,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681a97c7238',
  'title' => 'Maps',
  'fields' => array(
    array(
      'key' => 'field_5d681a9c872e7',
      'label' => 'Maps',
      'name' => 'maps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Map',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681aae872e8',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 6,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681caa470d6',
  'title' => 'Disclosures',
  'fields' => array(
    array(
      'key' => 'field_5d681cb4a2bfa',
      'label' => 'Disclosures',
      'name' => 'disclaimers',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Disclosure',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681cbea2bfb',
          'label' => 'Disclosure',
          'name' => 'disclaimer',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'interra_disclaimer',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 7,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681d03442fc',
  'title' => 'Comps',
  'fields' => array(
    array(
      'key' => 'field_5d681d0871b82',
      'label' => 'Sales Comps',
      'name' => 'sales_comps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d681d2b71b83',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Sales Comp',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681d2b71b83',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d681d3f71b84',
          'label' => 'Price Sold',
          'name' => 'price_sold',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d681d4f71b85',
          'label' => 'Differences',
          'name' => 'differences',
          'type' => 'textarea',
          'instructions' => 'List one difference per line.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5d681d9671b86',
          'label' => 'Photo',
          'name' => 'photo',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5d681da771b87',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
    array(
      'key' => 'field_5d681e4ae17fd',
      'label' => 'Rent Comps',
      'name' => 'rent_comps',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_5d681d2b71b83',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Rent Comp',
      'sub_fields' => array(
        array(
          'key' => 'field_5d681e4ae17fe',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5d681e4ae17ff',
          'label' => 'Rent',
          'name' => 'rent',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '$',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1800',
          'label' => 'Differences',
          'name' => 'differences',
          'type' => 'textarea',
          'instructions' => 'List one difference per line.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1801',
          'label' => 'Photo',
          'name' => 'photo',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5d681e4ae1802',
          'label' => 'Map',
          'name' => 'map',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_map',
          ),
          'taxonomy' => array(
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 8,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array(
  'key' => 'group_5d681e9b55c1a',
  'title' => 'Taxes',
  'fields' => array(
    array(
      'key' => 'field_5d681ea0720c9',
      'label' => 'Tax Year',
      'name' => 'tax_year',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681eb2720ca',
      'label' => 'Land Assessment',
      'name' => 'land_assessment',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681ef3720cb',
      'label' => 'Building Assesment',
      'name' => 'building_assesment',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '$',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d681f02720cc',
      'label' => 'Tax Rate',
      'name' => 'tax_rate',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '%',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'property_marketer',
      ),
    ),
  ),
  'menu_order' => 9,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

    endif;
  }
}

?>
